### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by diouk44** [tiramiseb/calaos-ha#1]
![Capture d’écran 2023-05-17 175016](https://github.com/tiramiseb/calaos-ha/assets/8988837/5df62e5a-482e-4a06-a56e-4c18db2cf522)

Calaos OS : V3 Beta 1
Hardware : Raspberry 3
HA : OS 10.1

**Comment by tiramiseb** [comment]
Hello,

Could you please check if there is something relevant in the log file?

In `/config/home-assistant.log`, the message should contain "Unexpected exception" and some details.

**Comment by tiramiseb** [comment]
:thinking: looking at my code, I realise you may not have anything in the log. I will improve this error message.

Meanwhile, can you confirm you can access your Calaos instance on https://192.168.1.60 ?

**Comment by diouk44** [comment]
Hi tiramiseb,

Logger: custom_components.calaos.config_flow
Source: custom_components/calaos/config_flow.py:49
Integration: Calaos ([documentation](https://github.com/tiramiseb/calaos-ha), [issues](https://github.com/tiramiseb/calaos-ha/issues))
First occurred: 18:29:45 (1 occurrences)
Last logged: 18:29:45

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/calaos/config_flow.py", line 49, in async_step_user
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pycalaos/client.py", line 97, in __init__
    self.reload_home()
  File "/usr/local/lib/python3.10/site-packages/pycalaos/client.py", line 122, in reload_home
    items[item._id] = item
AttributeError: 'NoneType' object has no attribute '_id'


Thanks for your help

**Comment by tiramiseb** [comment]
You probably have items types not supported by the library (simply because I only use a subset of them). I will take this opportunity to implement it!

I will first implement some helpful error messages, and at least ignore unknown items types instead of crashing. I will do something to be able to get the list of unknown items types from the log.

Stay tuned!

**Comment by tiramiseb** [comment]
I have released calaos-ha v0.1.3, which should work with unknown Calaos items, and write error messages about those items in the logs ("Unknown Calaos item type, using generic item for: xxx").

Could you please test it initialized without this unknown error, and see in the logs if you have these messages?

Thanks.

**Comment by diouk44** [comment]
I think, the problem is my internal items 

Logger: pycalaos.item
Source: /usr/local/lib/python3.10/site-packages/pycalaos/item.py:211
First occurred: 19:38:50 (1 occurrences)
Last logged: 19:38:50

Unknown Calaos item type, using generic item for: {'id': 'intern_0', 'name': 'Volets Auto', 'type': 'InternalBool', 'var_type': 'bool', 'visible': 'true', 'rw': 'true', 'gui_type': 'var_bool', 'state': 'false', 'io_type': 'inout'}

**Comment by tiramiseb** [comment]
I have released version 0.1.4, which should add support for this item (getting its status and changing it).

Could you please confirm?

**Comment by diouk44** [comment]
I delete all other internal item (internal var_int, time)  but I need my "WOVoletSmart" : see below

Logger: pycalaos.item
Source: /usr/local/lib/python3.10/site-packages/pycalaos/item.py:212
First occurred: 21:04:54 (1 occurrences)
Last logged: 21:04:54

Unknown Calaos item type, using generic item for: {'id': 'output_23', 'name': 'Volet', 'type': 'WOVoletSmart', 'var_type': 'string', 'visible': 'true', 'gui_type': 'shutter_smart', 'state': 'stop 0', 'io_type': 'output'}

**Comment by tiramiseb** [comment]
I could try and implement everything that exists in Calaos, but I don't have enough time, and it may never be used at all :sweat_smile: 

Therefore, don't hesitate to list all items types you are using! I **will** implement them. I want to improve the integration in a way that would be useful for real users.

**Comment by diouk44** [comment]
Ok thanks !

type="WIDigitalBP"
type="WIDigitalLong"
type="WODigital"
type="WOVoletSmart"

type="InPlageHoraire"

type="InternalBool"
type="InternalInt"
type="InternalString"

type="InputTime"
type="InputTimer"
type="scenario"

type="WebInputAnalog"
type="WebInputString"

**Comment by tiramiseb** [comment]
Hey!

I know it has been a few days already. Don't worry, I'm working on it.

Some of these items seem more complex than the ones I already had, therefore I have to rewrite some parts of the existing code to make everything right. It is taking more time than I expected.

**Comment by diouk44** [comment]
Ok thanks

**Comment by diouk44** [comment]
Hello
Have you progressed since last 2 month ?

**Comment by tiramiseb** [comment]
wow, that much time already! sorry :-(

I have been overwhelmed with other subjects, especially work-related.
I have not forgotten it, just had not much time to work on it.

I will try to dive into it soon.

**Comment by willoma** [comment]
Version 0.2.1 has been released!

Could you please test it?

**Comment by diouk44** [comment]
Thank you.

I have an issue with the WOvoletSmart  type :

Logger: homeassistant.components.cover
Source: custom_components/calaos/cover.py:29
Integration: Volets ([documentation](https://www.home-assistant.io/integrations/cover), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+cover%22))
First occurred: 11:42:05 (2 occurrences)
Last logged: 11:42:05

Error adding entities for domain cover with platform calaos
Error while setting up calaos platform for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 504, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 788, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/calaos/entity.py", line 30, in async_added_to_hass
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 267, in state
    if self.is_opening:
       ^^^^^^^^^^^^^^^
  File "/config/custom_components/calaos/cover.py", line 29, in is_opening
    return self.item.value["action"] == io.OutputShutterAction.UP
           ^^^^^^^^^^^^^^^
AttributeError: 'OutputShutterSmart' object has no attribute 'value'

**Comment by willoma** [comment]
Sorry, I used the wrong variable name :flushed: 

v0.2.2 should be better

**Comment by diouk44** [comment]
shutters appear closed while open
Up and down commands do not respond

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/calaos/cover.py:44
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 18:56:33 (3 occurrences)
Last logged: 18:57:35

[140110684416208] OutputShutterSmart.down() missing 1 required positional argument: 'value'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1957, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1997, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 845, in entity_service_call
    response_data = task.result()  # pop exception if have
                    ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1192, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 889, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 345, in async_close_cover
    await self.hass.async_add_executor_job(ft.partial(self.close_cover, **kwargs))
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/calaos/cover.py", line 44, in close_cover
    self.item.down()
TypeError: OutputShutterSmart.down() missing 1 required positional argument: 'value'

**Comment by willoma** [comment]
Thanks. It has been written in a hurry, without any possibility to test it in real life :disappointed: 

This error should be fixed in v0.2.3.

**Comment by diouk44** [comment]
No problem, we'll get there!
->but shutters appear closed while open and an other issue below :

Thank for everything

![image](https://github.com/willoma/calaos-ha/assets/8988837/42a3436b-fd24-425b-9732-616aeb4703a9)


Logger: homeassistant
Source: custom_components/calaos/cover.py:29
Integration: Calaos (documentation, issues)
First occurred: 22:08:53 (3 occurrences)
Last logged: 22:09:11

Error doing job: Exception in callback Entity.async_write_ha_state()
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 267, in state
    if self.is_opening:
       ^^^^^^^^^^^^^^^
  File "/config/custom_components/calaos/cover.py", line 29, in is_opening
    return self.item.state["action"] == io.OutputShutterAction.UP
           ~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: 'int' object is not subscriptable

**Comment by willoma** [comment]
With v0.2.4 maybe ? :slightly_smiling_face:

**Comment by diouk44** [comment]
V0.2.4 :
no error but 
When shutters are open:
shutters appear closed while open and the command down is masked
When shutters are closed:
shutters appear opened while close and the command up is masked

Physically all my shutters are closed but home assistant display :
![image](https://github.com/willoma/calaos-ha/assets/8988837/d4a2cbbc-adfa-4d55-a238-4f5aa13a64ec)

**Comment by willoma** [comment]
After a more careful reading of Calaos source code, it looks like Calaos' positions are the reverse of HA positions (Calaos up = 0%, HA up = 100%). The math to reverse these values has been added in v0.2.5. Could you please try?

**Comment by diouk44** [comment]
all works fine !  Thank you for all 👍

**Comment by willoma** [comment]
Fixed in v0.2.5 :)
