### ISSUE TITLE
Error adding entities for domain light with platform calaos

### ISSUE THREAD

**Issue by diouk44** [tiramiseb/calaos-ha#3]
Hello,

Since update home assistant core and calaos integration :

Logger: homeassistant.components.light
Source: helpers/entity_platform.py:619
Integration: Lumière (documentation, issues)
First occurred: 09:18:41 (2 occurrences)
Last logged: 09:18:41

Error adding entities for domain light with platform calaos
Error while setting up calaos platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: homeassistant.helpers.device_registry.DeviceRegistry.async_get_or_create() got multiple values for keyword argument 'config_entry_id'

**Comment by willoma** [comment]
I can confirm I have the same error after upgrading core. I'm checking what changed.

**Comment by willoma** [comment]
you may now update Calaos-HA :)
